### ISSUE TITLE
Model RX-A780 features not yet implemented

### ISSUE THREAD

**Issue by waltlillyman** [vigonotion/aiomusiccast#18]
The model  supports the feature:
ypao_volume
party_volume
party_mute
name_text_avr
hdmi_standby_through

Zone main of model RX-A780 supports the feature:
extra_bass
adaptive_drc
dts_dialogue_control
adaptive_dsp_level

Zone zone2 of model RX-A780 supports the feature:
extra_bass
mono

Thank you!
[Yamaha RX-A780 getFeatures response json.txt](https://github.com/vigonotion/aiomusiccast/files/7025726/Yamaha.RX-A780.getFeatures.response.json.txt)

**Comment by vigonotion** [comment]
Thank you! We already added these feature flags to our list in https://github.com/vigonotion/aiomusiccast/pull/15, so the next time we update the dependency in Home Assistant (which actually should be soon) the logs should disappear.

Do you want to automate any of these features? We didn't yet implement any logic for these features, but if you have a use case and can help us discover the undocumented parts of the REST-API, we could implement them

**Comment by waltlillyman** [comment]
@vigonotion Hi! I don't have a specific use case for these features, but since I own the device and have a working Home Assistant installation, I'm happy to help test the features and reply with output, if needed. I'm capable with Postman, curl, etc.
