### ISSUE TITLE
How do I join a speaker_group?

### ISSUE THREAD

**Issue by onkelbeh** [vigonotion/aiomusiccast#20]
Sorry, cannot get it working, all documentation I find is very outdated.
I'm on 2021.9.3, the integrated MusicCast (aiomusiccast-0.9.1) (at least HA's docu says) should provide a join routine.
But it tells there is no service musiccast/join. mini-media-player-bundle.js is 12.1.
I have added three RXV's (config flow).

Here's how it looks with platform set to mediaplayer:

<img width="612" alt="Bildschirmfoto 2021-09-05 um 17 34 13" src="https://user-images.githubusercontent.com/42828703/132132726-06cd7fc4-c7e7-4864-b1ea-33ffd339f309.png">

This is my custom card:
```
type: entities
entities:
  - type: custom:mini-media-player
    group: true
    entity: media_player.rxv_werkstatt
    name: RXV Werkstatt
    toggle_power: false
    artwork: cover
    hide:
      icon: true
      power_state: false
      source: false
    speaker_group:
      platform: media_player
      expanded: false
      entities:
        - entity_id: media_player.rxv_wohnen
          name: Wohnzimmer
        - entity_id: media_player.rxv_kueche
          name: Küche
  - type: custom:mini-media-player
    group: true
    entity: media_player.rxv_wohnen
    hide:
      icon: true
      controls: true
      progress: true
      source: true
      info: true
      power_state: false
  - type: custom:mini-media-player
    group: true
    entity: media_player.rxv_kueche
    hide:
      icon: true
      controls: true
      progress: true
      source: true
      info: true
      power_state: false
```

if I change the speaker_group platform to musiccast, it looks like this:

<img width="815" alt="Bildschirmfoto 2021-09-05 um 17 34 25" src="https://user-images.githubusercontent.com/42828703/132132719-e027de87-04aa-4261-a38d-0ca975b39ebb.png">

**Comment by onkelbeh** [comment]
Played around a bit, found a solution:

```yaml
service: media_player.join
target:
  entity_id:
    - media_player.rxv_wohnen
data:
  group_members: media_player.rxv_wohnen
```

would be a feature to find it in the doku.

**Comment by vigonotion** [comment]
That would be an issue for the Home Assistant repo and/or the mini-media-player card.

The join service is documented here:
https://www.home-assistant.io/integrations/media_player/#service-media_playerjoin

You can also take a look here: https://github.com/kalkih/mini-media-player/issues/528
on how to make the mini-media-player card work with the new integration
